"""Data models for EU project document processing and management."""

from typing import Literal, List

from pydantic import BaseModel, Field

PROJECT_LIST = [
    "SPECTRO", "EMAI4EU", "RESCHIP4EU", "ACHIEVE",
]


class LLMBasicAnswer(BaseModel):
    """Data model for basic LLM answers."""

    answer: str = Field(description="Answer generated by the LLM")


class LLMAnswerWithSources(LLMBasicAnswer):
    """Data model for LLM answers that include sources."""

    sources: List[dict] = Field(
        description="""
            List of sources used to generate the answer, each source is a dictionary with 'document_name' and 'page_numbers'.
            The document_name is a string ('Call Document', 'Proposal' or 'Grant Agreement'.
            The page_numbers is a string representing the page numbers in the document.
        """
    )

class ProjectExtraction(BaseModel):
    """Data model for extracting project-related information from user queries."""

    project_names: List[Literal["SPECTRO", "EMAI4EU", "RESCHIP4EU", "ACHIEVE"]] = Field(
        description="Name of the project the user is asking about"
    )

    confidence_scores: List[float] = Field(description="Confidence score between 0 and 1")

class ProjetFileData(BaseModel):
    """Data model containing file paths for project-related file documents."""
    project_name: str = Field(description="Name of the project")
    base_path: str = Field(description="Base path for the project")
    start_date: str = Field(description="Start date of the project")
    call_file: str = Field(description="Path to the call file")
    proposal_file: str = Field(description="Path to the proposal file")
    ga_file: str = Field(description="Path to the grant agreement file")


class ProjectData(BaseModel):
    """Data model representing a project's information and associated documents."""
    project_name: str = Field(description="Name of the project")
    start_date: str = Field(description="Start date of the project")
