""" Custom RAG Completion Function for OpenAI Evals
This module defines a custom completion function for evaluating the quality of responses generated by a Retrieval-Augmented Generation (RAG) system.
It uses OpenAI's API to score the responses based on relevance and completeness."""

from termcolor import colored

from euprojectsrag.rag_chain import RAGChain

if __name__ == "__main__":
    rag_chain = RAGChain()
    question = input(colored("Enter the question you want to ask to the project:\n", "green"))
    project_names =rag_chain.project_name_extraction(question)
    if len(project_names) == 0:
        answer = "No project found for the given prompt."
    elif len(project_names) == 1:
        answer = rag_chain.query_project(question, project_names[0][0])
    else:
        answer = rag_chain.query_projects(question, project_names)

    print(colored(answer, "green"))
