""" Custom RAG Completion Function for OpenAI Evals
This module defines a custom completion function for evaluating the quality of responses generated by a Retrieval-Augmented Generation (RAG) system.
It uses OpenAI's API to score the responses based on relevance and completeness."""

from termcolor import colored

from src.euprojectsrag.rag_chain import RAGChain

if __name__ == "__main__":
    rag_chain = RAGChain()
    question = input(colored("Enter the question you want to ask to the project:\n", "green"))
    asnwer = rag_chain.query_project(question)
    print(colored(asnwer, "green"))
